@base=http://localhost:8000

### Create a new session
POST {{base}}/apps/persona/users/u_123/sessions/s_123
Content-Type: application/json

### Create a persona from Linda Arlet
POST {{base}}/run
Content-Type: application/json

{
    "app_name": "persona",
    "user_id": "u_123",
    "session_id": "s_123",
    "new_message":
    {
        "role": "user",
        "parts": [{
            "text": "https://www.linkedin.com/in/linda-arlet-924b2427/"
        }]
    }
}